brokerport=1883
timer.repeatCount=100000

brokeraddress=broker-0-mqtt-0-svc.broker-f.svc.cluster.local
mqtt.remoteURI=tcp://broker-0-mqtt-0-svc.broker-f.svc.cluster.local:1883

mqtt.connectionTimeout=60
mqtt.keepAliveInterval=120
camel.component.seda.concurrentConsumers=20