status = INFO
name = PropertiesConfig

appender.stdout.type = Console
appender.stdout.name = stdout
appender.stdout.layout.type = PatternLayout
appender.stdout.layout.pattern = %d [%t] %-5p %c - %m%n

logger.jaas.name = org.apache.activemq.artemis.spi.core.security.jaas
logger.jaas.level = DEBUG
logger.ldap.name = javax.naming.ldap
logger.ldap.level = DEBUG

rootLogger.level = INFO
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = stdout
