remote.in.queue=inQueue
remote.in.queue.fqn=java:/jms/amq/queue/inQueue
remote.out.queue=outQueue
remote.out.queue.fqn=java:/jms/amq/queue/outQueue
jca.connection.factory=java:/RemoteJmsXA
user.name=quickuser
user.password=quick123+
external.context=java:global/remoteContext
use.jndi=false
#jndi.params=java.naming.factory.initial=org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory;java.naming.provider.url=tcp//rex:61616;java.naming.security.principal=quickuser;java.naming.security.credentials=quick123+
max.session=3
rebalance.connections=true
ha=true
ra.bind.name=remote-cluster





