brokerport=1883

quarkus.log.min-level=TRACE
quarkus.log.category."org.apache.camel.component.paho.mqtt5".level=TRACE
quarkus.log.category."org.eclipse.paho.mqttv5.client".level=TRACE

brokeraddress=broker-1-mqtt-0-svc.broker-f.svc.cluster.local
mqtt.remoteURI=tcp://broker-1-mqtt-0-svc.broker-f.svc.cluster.local:1883

mqtt.connectionTimeout=60
mqtt.keepAliveInterval=120
camel.component.seda.concurrentConsumers=20
