# Global Settings
include         /etc/openldap/schema/core.schema
include         /etc/openldap/schema/cosine.schema
include         /etc/openldap/schema/inetorgperson.schema
include         /etc/openldap/schema/nis.schema

pidfile         /var/run/openldap/slapd.pid
argsfile        /var/run/openldap/slapd.args

# TLS Settings
TLSCACertificateFile    /etc/openldap/certs/ca.crt
TLSCertificateFile      /etc/openldap/certs/ldap.crt
TLSCertificateKeyFile   /etc/openldap/certs/ldap.key

# Config Database Permissions
database config
access to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" manage by * none

# Main Database (MDB)
database        mdb
suffix          "dc=redhat,dc=com"
rootdn          "cn=admin,dc=redhat,dc=com"
rootpw          admin
directory       /var/lib/ldap

index   objectClass eq,pres
index   ou,cn,mail,surname,givenname eq,pres,sub
